AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable
  SuggestExtensions: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

# RSpec describe/context blocks and rake task files are naturally large
Metrics/BlockLength:
  Exclude:
    - "spec/**/*_spec.rb"
    - "*.gemspec"
    - "**/*.rake"

# Binary class has multiple core responsibilities (decrypt, encrypt, edit, version)
Metrics/ClassLength:
  Exclude:
    - "lib/sops_rails/binary.rb"
